### ISSUE TITLE
license to use? (not an issue)

### ISSUE THREAD

**Issue by hyusetiawan** [fishfishher/Game-Solitaire#1]
I am interested in hosting the solitaire on [unopico](https://unopi.co), there is no usage license however and I dont want to step on anyone's toes :) Mind adding a license to use?

**Comment by michelleheh** [comment]
Wahyu,

Thank you for asking about the license. I'm thrilled that you wanted to host my first JS project!!  A license just got added, so feel free to use the code. Be aware that the game is not perfect. See the Further To Do in the readme.

Regards,
Xiaoyu
